### ISSUE TITLE
npm ERR! path /root/fonts/node_modules/fontnik

### ISSUE THREAD

**Issue by raphael10-collab** [openmaptiles/fonts#22]
root@vmi1046457:~# git clone https://github.com/openmaptiles/fonts.git
    Cloning into 'fonts'...
    remote: Enumerating objects: 8699, done.
    remote: Counting objects: 100% (321/321), done.
    remote: Compressing objects: 100% (281/281), done.
    remote: Total 8699 (delta 51), reused 40 (delta 40), pack-reused 8378
    Receiving objects: 100% (8699/8699), 149.06 MiB | 23.49 MiB/s, done.
    Resolving deltas: 100% (121/121), done.
    root@vmi1046457:~# cd fonts/
    root@vmi1046457:~/fonts# ls -lah
    total 52K
    drwxr-xr-x  8 root root 4.0K Mar 22 17:04 .
    drwx------ 12 root root 4.0K Mar 22 17:03 ..
    drwxr-xr-x  8 root root 4.0K Mar 22 17:04 .git
    -rw-r--r--  1 root root   21 Mar 22 17:04 .gitignore
    -rw-r--r--  1 root root 1.4K Mar 22 17:04 README.md
    -rw-r--r--  1 root root 4.2K Mar 22 17:04 generate.js
    drwxr-xr-x  2 root root 4.0K Mar 22 17:04 metropolis
    drwxr-xr-x  2 root root 4.0K Mar 22 17:04 noto-sans
    drwxr-xr-x  2 root root 4.0K Mar 22 17:04 open-sans
    -rw-r--r--  1 root root  216 Mar 22 17:04 package.json
    drwxr-xr-x  2 root root 4.0K Mar 22 17:04 pt-sans
    drwxr-xr-x  2 root root 4.0K Mar 22 17:04 roboto

    root@vmi1046457:~/fonts# npm install
    npm WARN deprecated node-pre-gyp@0.14.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
    npm ERR! code 1
    npm ERR! path /root/fonts/node_modules/fontnik
    npm ERR! command failed
    npm ERR! command sh -c node-pre-gyp install --fallback-to-build=true
    npm ERR! make: Entering directory '/root/fonts/node_modules/fontnik/build'
    npm ERR!   ACTION binding_gyp_action_before_build_target_install_deps mason_packages
    npm ERR! Downloading https://s3.amazonaws.com/mason-binaries/linux-x86_64/clang++/10.0.0.tar.gz
    npm ERR!   TOUCH Release/obj.target/action_before_build.stamp
    npm ERR!   CXX(target) Release/obj.target/fontnik/src/node_fontnik.o
    npm ERR! make: Leaving directory '/root/fonts/node_modules/fontnik/build'
    npm ERR! Failed to execute '/root/.nvm/versions/node/v18.15.0/bin/node /root/.nvm/versions/node/v18.15.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build=true --module=/root/fonts/node_modules/fontnik/lib/binding/fontnik.node --module_name=fontnik --module_path=/root/fonts/node_modules/fontnik/lib/binding --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
    npm ERR! node-pre-gyp info it worked if it ends with ok
    npm ERR! node-pre-gyp info using node-pre-gyp@0.14.0
    npm ERR! node-pre-gyp info using node@18.15.0 | linux | x64
    npm ERR! node-pre-gyp WARN Using needle for node-pre-gyp https download 
    npm ERR! node-pre-gyp info check checked for "/root/fonts/node_modules/fontnik/lib/binding/fontnik.node" (not found)
    npm ERR! node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/fontnik/v0.6.0/Release/node-v108-linux-x64.tar.gz
    npm ERR! node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/fontnik/v0.6.0/Release/node-v108-linux-x64.tar.gz
    npm ERR! node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/fontnik/v0.6.0/Release/node-v108-linux-x64.tar.gz 
    npm ERR! node-pre-gyp WARN Pre-built binaries not found for fontnik@0.6.0 and node@18.15.0 (node-v108 ABI, glibc) (falling back to source compile with node-gyp) 
    npm ERR! node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/fontnik/v0.6.0/Release/node-v108-linux-x64.tar.gz 
    npm ERR! gyp info it worked if it ends with ok
    npm ERR! gyp info using node-gyp@9.3.1
    npm ERR! gyp info using node@18.15.0 | linux | x64
    npm ERR! gyp info ok 
    npm ERR! gyp info it worked if it ends with ok
    npm ERR! gyp info using node-gyp@9.3.1
    npm ERR! gyp info using node@18.15.0 | linux | x64
    npm ERR! gyp info find Python using Python version 3.10.6 found at "/usr/bin/python3"
    npm ERR! gyp info spawn /usr/bin/python3
    npm ERR! gyp info spawn args [
    npm ERR! gyp info spawn args   '/root/.nvm/versions/node/v18.15.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
    npm ERR! gyp info spawn args   'binding.gyp',
    npm ERR! gyp info spawn args   '-f',
    npm ERR! gyp info spawn args   'make',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   '/root/fonts/node_modules/fontnik/build/config.gypi',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   '/root/fonts/node_modules/fontnik/common.gypi',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   '/root/.nvm/versions/node/v18.15.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   '/root/.cache/node-gyp/18.15.0/include/node/common.gypi',
    npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
    npm ERR! gyp info spawn args   '-Dvisibility=default',
    npm ERR! gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/18.15.0',
    npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/root/.nvm/versions/node/v18.15.0/lib/node_modules/npm/node_modules/node-gyp',
    npm ERR! gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/18.15.0/<(target_arch)/node.lib',
    npm ERR! gyp info spawn args   '-Dmodule_root_dir=/root/fonts/node_modules/fontnik',
    npm ERR! gyp info spawn args   '-Dnode_engine=v8',
    npm ERR! gyp info spawn args   '--depth=.',
    npm ERR! gyp info spawn args   '--no-parallel',
    npm ERR! gyp info spawn args   '--generator-output',
    npm ERR! gyp info spawn args   'build',
    npm ERR! gyp info spawn args   '-Goutput_dir=.'
    npm ERR! gyp info spawn args ]
    npm ERR! gyp info ok 
    npm ERR! gyp info it worked if it ends with ok
    npm ERR! gyp info using node-gyp@9.3.1
    npm ERR! gyp info using node@18.15.0 | linux | x64
    npm ERR! gyp info spawn make
    npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
    npm ERR! basename: missing operand
    npm ERR! Try 'basename --help' for more information.
    npm ERR! * Downloading binary package https://mason-binaries.s3.amazonaws.com/headers/boost/1.67.0.tar.gz
    npm ERR! * Installed binary package at /root/fonts/node_modules/fontnik/mason_packages/headers/boost/1.67.0
    npm ERR! basename: missing operand
    npm ERR! Try 'basename --help' for more information.
    npm ERR! * Linking /root/fonts/node_modules/fontnik/mason_packages/headers/boost/1.67.0
    npm ERR! * Links will be inside /root/fonts/node_modules/fontnik/mason_packages/.link/
    npm ERR! * Using 'cp' for symlinking
    npm ERR! * Done linking /root/fonts/node_modules/fontnik/mason_packages/headers/boost/1.67.0
    npm ERR! * Downloading binary package https://mason-binaries.s3.amazonaws.com/linux-x86_64/freetype/2.7.1.tar.gz
    npm ERR! * Installed binary package at /root/fonts/node_modules/fontnik/mason_packages/linux-x86_64/freetype/2.7.1
    npm ERR! * Linking /root/fonts/node_modules/fontnik/mason_packages/linux-x86_64/freetype/2.7.1
    npm ERR! * Links will be inside /root/fonts/node_modules/fontnik/mason_packages/.link/
    npm ERR! * Using 'cp' for symlinking
    npm ERR! * Done linking /root/fonts/node_modules/fontnik/mason_packages/linux-x86_64/freetype/2.7.1
    npm ERR! * Downloading binary package https://mason-binaries.s3.amazonaws.com/headers/protozero/1.6.8.tar.gz
    npm ERR! * Installed binary package at /root/fonts/node_modules/fontnik/mason_packages/headers/protozero/1.6.8
    npm ERR! * Linking /root/fonts/node_modules/fontnik/mason_packages/headers/protozero/1.6.8
    npm ERR! * Links will be inside /root/fonts/node_modules/fontnik/mason_packages/.link/
    npm ERR! * Using 'cp' for symlinking
    npm ERR! * Done linking /root/fonts/node_modules/fontnik/mason_packages/headers/protozero/1.6.8
    npm ERR! * Downloading binary package https://mason-binaries.s3.amazonaws.com/headers/sdf-glyph-foundry/0.1.1.tar.gz
    npm ERR! * Installed binary package at /root/fonts/node_modules/fontnik/mason_packages/headers/sdf-glyph-foundry/0.1.1
    npm ERR! * Linking /root/fonts/node_modules/fontnik/mason_packages/headers/sdf-glyph-foundry/0.1.1
    npm ERR! * Links will be inside /root/fonts/node_modules/fontnik/mason_packages/.link/
    npm ERR! * Using 'cp' for symlinking
    npm ERR! * Done linking /root/fonts/node_modules/fontnik/mason_packages/headers/sdf-glyph-foundry/0.1.1
    npm ERR! * Downloading binary package https://mason-binaries.s3.amazonaws.com/headers/gzip-hpp/0.1.0.tar.gz
    npm ERR! * Installed binary package at /root/fonts/node_modules/fontnik/mason_packages/headers/gzip-hpp/0.1.0
    npm ERR! * Linking /root/fonts/node_modules/fontnik/mason_packages/headers/gzip-hpp/0.1.0
    npm ERR! * Links will be inside /root/fonts/node_modules/fontnik/mason_packages/.link/
    npm ERR! * Using 'cp' for symlinking
    npm ERR! * Done linking /root/fonts/node_modules/fontnik/mason_packages/headers/gzip-hpp/0.1.0
    npm ERR! <command-line>: error: "_GLIBCXX_USE_CXX11_ABI" redefined
    npm ERR! <command-line>: note: this is the location of the previous definition
    npm ERR! make: *** [fontnik.target.mk:156: Release/obj.target/fontnik/src/node_fontnik.o] Error 1
    npm ERR! gyp ERR! build error 
    npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
    npm ERR! gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/versions/node/v18.15.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:203:23)
    npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
    npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
    npm ERR! gyp ERR! System Linux 5.15.0-53-generic
    npm ERR! gyp ERR! command "/root/.nvm/versions/node/v18.15.0/bin/node" "/root/.nvm/versions/node/v18.15.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build=true" "--module=/root/fonts/node_modules/fontnik/lib/binding/fontnik.node" "--module_name=fontnik" "--module_path=/root/fonts/node_modules/fontnik/lib/binding" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v108"
    npm ERR! gyp ERR! cwd /root/fonts/node_modules/fontnik
    npm ERR! gyp ERR! node -v v18.15.0
    npm ERR! gyp ERR! node-gyp -v v9.3.1
    npm ERR! gyp ERR! not ok 
    npm ERR! node-pre-gyp ERR! build error 
    npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/root/.nvm/versions/node/v18.15.0/bin/node /root/.nvm/versions/node/v18.15.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build=true --module=/root/fonts/node_modules/fontnik/lib/binding/fontnik.node --module_name=fontnik --module_path=/root/fonts/node_modules/fontnik/lib/binding --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
    npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/root/fonts/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
    npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
    npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
    npm ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
    npm ERR! node-pre-gyp ERR! System Linux 5.15.0-53-generic
    npm ERR! node-pre-gyp ERR! command "/root/.nvm/versions/node/v18.15.0/bin/node" "/root/fonts/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build=true"
    npm ERR! node-pre-gyp ERR! cwd /root/fonts/node_modules/fontnik
    npm ERR! node-pre-gyp ERR! node -v v18.15.0
    npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.14.0
    npm ERR! node-pre-gyp ERR! not ok
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /root/.npm/_logs/2023-03-22T16_05_23_416Z-debug-0.log
    root@vmi1046457:~/fonts# nano package.json 
    root@vmi1046457:~/fonts# 

node : v18.15.0
O.S. : Ubuntu 22.04

**Comment by raphael10-collab** [comment]
root@vmi1046457:~/fonts# sudo npm install
    npm WARN deprecated node-pre-gyp@0.14.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
    
    added 80 packages, and audited 81 packages in 7s
    
    3 packages are looking for funding
      run `npm fund` for details
    
    found 0 vulnerabilities
